### ISSUE TITLE
ideas for improvement

### ISSUE THREAD

**Issue by rehmulus** [generoi/phpHyphenator#1]
1. The exclude tags are really excluded, not just ignored. It'd be better (for me) if you just don't hyphenate everything inside the tags.
2. Html Entities are hyphenated so that some show up in plain text. Example: "&ldquo;" will be printed as "&ldquo;", not as a quotation mark.

**Comment by oxyc** [comment]
Sorry we dont provide maintenance for this, it's a direct fork of  http://phphyphenator.yellowgreen.de/

edit: which apparently isn't there anymore
